[package]
name = "conway"
version = "0.1.0"
authors = ["panicbit <panicbit@users.noreply.github.com>"]

[dependencies]
rand = "0.3"
#rustbox = "0.5"

[dependencies.rustbox]
git = "https://github.com/panicbit/rustbox"
branch = "mouse_events"

